export const actionTypes = {
  UPDATE_RELEVANCE_FILTER: 'UPDATE_RELEVANCE_FILTER',
  UPDATE_STOPS_FILTER: 'UPDATE_STOPS_FILTER',
  REQUEST_TICKETS: 'REQUEST_TICKETS',
  RECEIVE_TICKETS: 'RECEIVE_TICKETS',
  RECEIVE_SEARCH_ID: 'RECEIVE_SEARCH_ID',
}
